version: 2
jobs:
  build:
    docker:
    - image: circleci/node:latest
    steps:
    - checkout
    - restore_cache:
        name: Restore Yarn Package Cache
        keys:
        - yarn-packages-{{ checksum "yarn.lock" }}
    - run:
        name: Install Dependencies
        command: yarn
    - save_cache:
        name: Save Yarn Package Cache
        key: yarn-packages-{{ checksum "yarn.lock" }}
        paths:
        - ~/.cache/yarn
    - run:
        name: Run test with coverage
        command: yarn test:unit --coverage
    - run:
        name: Build the project
        command: yarn build
    - store_test_results:
        path: coverage
    - store_artifacts:
        path: coverage
  deploy:
    machine:
      enabled: true
    steps:
    - run:
        name: Deploy over SSH
        command: |
          ssh $SSH_USER@$SSH_HOST
          cd /var/www/html/$CIRCLE_PROJECT_REPONAME
          git pull
          yarn build

workflows:
  version: 2
  build-and-deploy:
    jobs:
    - build
    - deploy:
        requires:
        - build
#        filters:
#          branches:
#            only: master