version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn global add codecov
      - run: yarn
      - save_cache:
          paths:
            - node_modules/
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test:unit
      - store_test_results:
          path: test/unit/coverage/clover.xml
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "cd /var/www/html/ && mkdir -p $CIRCLE_PROJECT_REPONAME"